---
version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    groups:
      cicd:
        patterns:
          - "*"

  - package-ecosystem: bun
    directory: /
    schedule:
      interval: daily
    cooldown:
      semver-major-days: 3
      semver-minor-days: 2
      semver-patch-days: 2
    groups:
      bun-toolkit:
        patterns:
          - "@actions/*"
      bun-dev:
        patterns:
          - "*"

  # - package-ecosystem: opentofu # https://github.com/opentofu/opentofu/issues/1236
  #   directories:
  #     - /sample/bucket
  #     - /sample/instance
  #   schedule:
  #     interval: weekly
  #   groups:
  #     terraform:
  #       patterns:
  #         - "*"
