---
name: Dependabot auto-merge

# Auto-merge Dependabot PRs if checks pass. It only runs for PRs created by the
# `dependabot[bot]` user.

on: pull_request_target

permissions:
  contents: write
  pull-requests: write

jobs:
  Auto-merge:
    runs-on: ubuntu-24.04
    if: github.actor == 'dependabot[bot]'

    steps:
      - name: Enable auto-merge
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
        run: gh pr merge --auto --squash "$PR_URL"
